[package]
name = "transit"
version = "0.1.0"
authors = ["Al McElrath <hello@yrns.org>"]
edition = "2018"

[features]
# Just for development and ra:
default = ["editor"]

editor = ["druid"]

[workspace]
members = ["edit"]

[dependencies]
petgraph = { version = "0.5.0", features = ["serde-1"] }
serde = { version = "1.0.104", features = ["rc"] }
ron = "0.5.1"
serde_json = "1.0.44"
anyhow = "1.0.26"
once_cell = "1.3.1"
#kurbo = { git = "https://github.com/linebender/kurbo.git", rev = "0ed65ac", features = ["serde"], optional = true }
# for druid::Data?
druid = { version = "0.7.0", optional = true }

[dev-dependencies]
rustyline = "6.0.0"
#serde_traitobject = "0.2.4"
