[package]
name = "transit"
version = "0.1.0"
authors = ["Al McElrath <hello@yrns.org>"]
edition = "2018"

[features]
# Just for development and ra:
default = []

#edit = ["egui_egui"]

[workspace]
members = ["edit_egui"]

[dependencies]
petgraph = { version = "0.6", features = ["serde-1"] }
serde = "1.0"
ron = "0.8"
once_cell = "1.3.1"
thiserror = "1.0.37"
#kurbo = { git = "https://github.com/linebender/kurbo.git", rev = "0ed65ac", features = ["serde"], optional = true }
# for druid::Data?
#druid = { version = "0.7.0", optional = true }

[dev-dependencies]
rustyline = "6.0.0"
#serde_traitobject = "0.2.4"
