[package]
name = "transit"
version = "0.1.0"
authors = ["Al McElrath <hello@yrns.org>"]
edition = "2018"

[workspace]
members = ["edit"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = { version = "0.5.0", features = ["serde-1"] }
serde = { version = "1.0.104", features = ["rc"] }
ron = "0.5.1"
serde_json = "1.0.44"
anyhow = "1.0.26"
once_cell = "1.3.1"
kurbo = "0.5.8"
#druid-derive = { path = "../druid/druid-derive" }
druid = { path = "../druid/druid" }

[dev-dependencies]
rustyline = "6.0.0"
#serde_traitobject = "0.2.4"
