[package]
name = "edit_egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serde"]
serde = ["dep:serde", "eframe/persistence"]

[dependencies]
transit = { path = ".." }
# need to make a separate crate for the bin to have differing deps
#egui = "0.19.0"
#eframe = "0.19.0"
eframe = { version = "0.1.0", path = "eframe-dynamic", package = "eframe-dynamic" }
serde = { version = "1", optional = true, features = ["derive"] }

[[bin]]
name = "transit"
